---
title: "Fiddler Crabs"
author: "Paloma Cartwright"
date: "20/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(kableExtra)
```

```{r, include=FALSE}
crab_size <- read_csv(here::here("data", "CrabBodySize.csv")) %>% 
  clean_names()
```

```{r, fig.alt = "Jitterplot showing the size of Fiddler Crabs by latitude. The Bare Cove Park has the largest crab size observed.", fig.cap = "Graph of carapace width (mm) vs latitude", echo=FALSE}
ggplot(crab_size, aes(y = carapace_width, x = latitude)) +
  geom_jitter(aes(color = site)) +
  labs(title = "Size of Fiddler Crabs by Location",
       x = "Latitude",
       y ="Carapace Width (mm)",
       color = "Site")


```

```{r, include=FALSE}
summ_table <- crab_size %>% 
  group_by(site) %>% 
  summarize(mean = round(mean(carapace_width, na.rm = TRUE), 2), 
            std = round(sd(carapace_width, na.rm = TRUE), 2), 
            count = n())
```

```{r, echo = FALSE}
summ_table %>% 
  kable(col.names = c("Site", "Mean (mm)", "
                      Standard Deviation (mm)", "Total Sample Size"), 
        caption = "Summary Table of Calculations by Site", 
        ) %>% 
  kable_styling(full_width = FALSE, position = "left") %>% 
  kable_classic() %>% 
  column_spec(1, bold = TRUE, background = "lightgray") %>% 
  row_spec(0, bold = TRUE, background = "lightblue")
```

```{r, include = FALSE}
test <- crab_size %>%
  group_by(site) %>% 
  summarize(mean_size = round(mean(carapace_width), 2),
            mean_water = round(mean(matw), 2))
```

```{r, fig.alt = "Scatterplot showing the mean size of Fiddler Crabs vs mean water temperature. On average, cooler water produces larger crabs.", fig.cap = "Graph of mean carapace width (mm) vs mean water temperature (degrees Celsius)", echo=FALSE}
ggplot(test, aes(x = mean_water, y = mean_size)) +
  geom_point(aes(color = site)) +
  labs(title = "Average Carapace Width vs. Average Water Temperature",
       x = "Average Water Temperature (degrees Celsius)",
       y = "Average Size (mm)",
       color = "Site")


```

